name: Scheduled Merge Remote Action

# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
# │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
# │ │ │ │ │
# │ │ │ │ │
# │ │ │ │ │
# * * * * *
# Operator	Description	Example
# *	Any value	* * * * * runs every minute of every day.
# ,	Value list separator	2,10 4,5 * * * runs at minute 2 and 10 of the 4th and 5th hour of every day.
# -	Range of values	0 4-6 * * * runs at minute 0 of the 4th, 5th, and 6th hour.
# /	Step values	20/15 * * * * runs every 15 minutes starting from minute 20 through 59 (minutes 20, 35, and 50).

on: 
  push:
  schedule:
    - cron: '0 0,12 * * *'
    # runs at minutes 0 of 0 and 12th hour of everyday

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: repacker             # set the branch to merge to
          fetch-depth: 0 
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: vmangos/core      # set the upstream repo
          upstream-branch: development   # set the upstream branch to merge from
          branch: repacker          # set the branch to merge to